"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.productsDD = void 0;
let description = 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rem illum amet excepturi praesentium. Quas incidunt sint exercitationem officiis nemo officia voluptas porro vitae, distinctio, perferendis delectus doloremque id impedit recusandae.';
let titles = [
    'D rose 11',
    'lorem novax',
    'rayzen up_74',
    'ccdddd121',
    'sequence_69',
    'node_13',
    'sequence z9_55',
    'destroy_90',
    'tiger_30',
    'Own street 87',
    'pytorch_41',
    'modern_67',
    'tiger_5',
    'own game',
    'D roky x5',
    'gustavy',
    'tiger_92',
    'the extreme rose',
    'postgres_26',
    'postgres_39',
    'sequence up_23',
    'sequence up_2',
    'pro boost',
    'knn 50x_98',
    'stroke row_7',
    'sigma_5',
    'donovan x3',
    'OWNTHEGAME',
    'brista 07_69',
    'postgres z9_81',
    'node 50x_43',
    'bogger z9_38',
    'brista_31',
    'massive z9_40',
    'node up_0',
    'sigmoid_39',
    'ml-pro 07_61',
    'brista 50x_37',
    'stroke row_26',
    'destroy row_15',
    'light up_37',
    'pytorch_57',
    'intel z9_61',
    'ml-pro row_25',
    'tiger up_90',
    'bogger 07_14',
    'sigmoid up_76',
    'sigma 07_52',
    'sigma row_41',
    'postgres z9_79',
    'stroke up_91',
    'brista_47',
    'sigmoid z9_41',
    'conva row_79',
];
let images = [
    [
        'http://drive.google.com/uc?export=view&id=1VEDDtQD49ZufGLVxcuLAR4dC4FJqFkKd',
        'http://drive.google.com/uc?export=view&id=1Ifx6_50HusMlq7m8YX_7aa5VgDQarLr0',
        'http://drive.google.com/uc?export=view&id=1iFgecFjezgiHElMFpJoCPj8gMJUJcHDu',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1sWGofYKUcjdb9wtNRpXjtvg5o_KawJn6',
        'http://drive.google.com/uc?export=view&id=17tIMPXyk_MirgDsyGrvccVCLtzx2XG3e',
        'http://drive.google.com/uc?export=view&id=1Jw6SG9DeLCNE8JGbEghz_rKL0Bw69hty',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1Ud0FCY8O6hdeDg9MxJ1EjZHzOoJShDFX',
        'http://drive.google.com/uc?export=view&id=1psALF_EAbn-_XFkwbkJUUzV1tZfCGHfm',
        'http://drive.google.com/uc?export=view&id=1FboVJuKEnU7CIhQCtsEv-sGxexIgY1RS',
    ],
    [
        'http://drive.google.com/uc?export=view&id=16k65eIU0Vl5OGxC8Co4J0FFKBvjMyMHG',
        'http://drive.google.com/uc?export=view&id=1kCwXdjUKSd9Ook2JIiBhqOTGEVEqsAbW',
        'http://drive.google.com/uc?export=view&id=1lVC-OJHeQHrorMyRmw99oUhCHFSYgq54',
        'http://drive.google.com/uc?export=view&id=1DNYVaKgNrs9ij1PpT7l4lCLT_ATPvb7y',
        'http://drive.google.com/uc?export=view&id=1oqF56LgaGSU7iRrwbtQnz8KsHGJhFBWP',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1hjd-dO23t1PzpqFOTADbrWKoN_hHNxC4',
        'http://drive.google.com/uc?export=view&id=1YI_nDnsc4MXqmcHKqyfxlRoFjxBGAEfN',
        'http://drive.google.com/uc?export=view&id=1_VzB_rr30j2P2rjezW0zkX_UCZQsGcdk',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1HnWHysT2XOyhlvyiQrhdp51IAXQQ1LKh',
        'http://drive.google.com/uc?export=view&id=1B9gg-Xtod8MRYxfnXrUrBnveoZkA0GLp',
        'http://drive.google.com/uc?export=view&id=1DDPH2h4zPnY1ATRPcuIxx1B5KbZw_za2',
    ],
    [
        'http://drive.google.com/uc?export=view&id=16LBtmvVZbHkjjI6yTSVyOeFNXqvJzCEo',
        'http://drive.google.com/uc?export=view&id=1inVZI0gzbg2lydQpOK-KDqrTwUpH6uOI',
        'http://drive.google.com/uc?export=view&id=1m3S4HgTh5Lv9Px66sN921S-8fVwmIJLq',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1IdkBYxAtdTAEk2Jtq3mKjpU2FR9Fk95A',
        'http://drive.google.com/uc?export=view&id=1akYmBNodtVzYdPEDPEQv1rIfbA_jC_jW',
        'http://drive.google.com/uc?export=view&id=1L_KBUsbhoOYTNAjVIT3of6i_Y2AuSzf2',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1v1y3Ztu5TKn1gaAAZxQizUofM_WYcmyj',
        'http://drive.google.com/uc?export=view&id=1mniOr-qS-Hm564nRP7QQHFM2_QXEDAZI',
        'http://drive.google.com/uc?export=view&id=1A9k1kysb39-beBPNyh76kOJ21rfVsfOf',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1FOaaJXC-eJQxJhLFdbl4G6a3Dc0xyXd-',
        'http://drive.google.com/uc?export=view&id=1NssBSgHDoB2QoJeEwMyVmz4TLVSgIHvC',
        'http://drive.google.com/uc?export=view&id=1a_19XxabV1jxEvUZjVL01HilG0BAsyBM',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1IQkiMdG1WYIT9xaubEwqOgPpkQwpjn8n',
        'http://drive.google.com/uc?export=view&id=1-otCJRRQt0udUHOkE7LKgVTKUAfeVUCc',
        'http://drive.google.com/uc?export=view&id=1_fuRpx_HQIppKQLmvA2ZVzc5ZH_eVMZ_',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1RHJ63diVGOWuSpLd192eCWJpKhdJbiOY',
        'http://drive.google.com/uc?export=view&id=12Jw7hzg8p8n691mewqLk31OPL2t61cLT',
        'http://drive.google.com/uc?export=view&id=18MeHoNwIHh0WKuRygNF1AQt5799gG1ez',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1mGFWXxUdQjr5La-RkdtQQFjVjxX2QHak',
        'http://drive.google.com/uc?export=view&id=1BQi_QYjZ3dRO7A_CSBuEFLz52IByRgdG',
        'http://drive.google.com/uc?export=view&id=1Xi1_KUXzPLYhsUs_sRYIIVjKuCTCmSpt',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1J-2xM2_xVtfLz8EzGXHFFBg-zR4vdfBq',
        'http://drive.google.com/uc?export=view&id=1fnBYJAhRmtiLLR5X9MUjX7hbZhCXiqLH',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1EtivOnp3ZRHoHWeZCOlE16mTgJ4m4ZIM',
        'http://drive.google.com/uc?export=view&id=1NzmEmgHmOgB_CG_8Ye1RAixRI0U7MkkV',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1g5UMPPgqQse650LY4ra9suA5wgxK37q5',
        'http://drive.google.com/uc?export=view&id=109QapdwU_y0V9XngIef9QkTP_zHehvbN',
        'http://drive.google.com/uc?export=view&id=1RVxpF_rEBuWXRrBEtKgiAJ_1VDWnLje8',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1cD3eU131pclbJPw5d9qStms_d8zo3ilc',
        'http://drive.google.com/uc?export=view&id=1eeuKd3oMfUeU4hE8g59jw0p_e4aglV8E',
        'http://drive.google.com/uc?export=view&id=1PrPda3KpkD9LkrwRe00ctdPVW8dNFjsC',
    ],
    [
        'http://drive.google.com/uc?export=view&id=17A3osbD8P3zYkBo4y8qXLYlOCmUU0fkl',
        'http://drive.google.com/uc?export=view&id=1SBhMdZIghmuIIQls6SMhIdgMrxbG7c6T',
        'http://drive.google.com/uc?export=view&id=1mEO83PZqfbyQBxKVvpbSDgOFNFub0JTD',
    ],
    [
        'http://drive.google.com/uc?export=view&id=16TsFh8O2urOrNRDwI6iDp8iZuZrluXY5',
        'http://drive.google.com/uc?export=view&id=1LbClIShMIEeW4KUSrHDPkKjQl-ZmKCvQ',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1GM6gvK0PUfAr7EcyQbBpP3toGH33KSNm',
        'http://drive.google.com/uc?export=view&id=1zXybeJMnQiZHbb8b0ANSQupbRwKLuxQ_',
        'http://drive.google.com/uc?export=view&id=19bvzZHP3sK4cZAKwHI8w74L5QUtwLBNb',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1vkhTPg-pb25j_TlldJr0o899HnVR3JUu',
        'http://drive.google.com/uc?export=view&id=1WJYjYoFBX0wr-lg2kMaBhf19obM-q2yM',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1MQvanoYzQMldvelEKJf7inWxIuYSih3G',
        'http://drive.google.com/uc?export=view&id=190GIn6c1fTeT7OIPUU4qvKqHTTQmyXVU',
        'http://drive.google.com/uc?export=view&id=1i-gGaROtWYg3ChgbOJq188xJwH7MYXlS',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1ZQ2I1MyxmcGWTrFNElU3KhBSoN_fZEJr',
        'http://drive.google.com/uc?export=view&id=1EDPZgvUPr7YVZvFlKfWyTgmU_NcDHFrP',
        'http://drive.google.com/uc?export=view&id=1FmHGnA3hmclGtha4rPWMngbSlh7Kbe9y',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1aj1MxDK1yoToykilVPI0TUjM9fPEJ_4s',
        'http://drive.google.com/uc?export=view&id=1sXyFPRQqBDbpDgKQnKF-6ItUqULYOIMa',
        'http://drive.google.com/uc?export=view&id=13gLhv_-t6sfVS6i7uXXVKPIrXx4XMpBj',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1rUGJLxBV_3waiGr5tpopZlSRxEHlk_iz',
        'http://drive.google.com/uc?export=view&id=1p7_eGD4gyiqcMyZMmQYngdjGuGrXa2dn',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1JLMeQn-FD6oTFJyPAMd18k8kBcQYGGV6',
        'http://drive.google.com/uc?export=view&id=1QDQVXlqjZPhXsUMmnCuReI91mflJ-lsg',
        'http://drive.google.com/uc?export=view&id=1-4uM6bGXaxi7UJri35004RF1nTIVDNYb',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1HWh4M3Hz80tor3U8FLZyqJ8f5ecsMBYn',
        'http://drive.google.com/uc?export=view&id=1WMXoa3m71jK8eZUa45CpVc-qWTloIQx9',
        'http://drive.google.com/uc?export=view&id=1cOYyQsvzKqLN6jzNcr_jghgi4noW29FX',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1WExko6wdeds7eVOdyhpVTm7xpSUjYhjL',
        'http://drive.google.com/uc?export=view&id=1b4OuQc6ld_hq-jRVOLWvIvlBywImI02V',
        'http://drive.google.com/uc?export=view&id=1iseSCsN4_t0ACQXF9mKPviqBGARqebIa',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1Nz_tcD7qhUYmfJIQepP3uMFz9hqptFqu',
        'http://drive.google.com/uc?export=view&id=1Zd6JFnOPjbs4xFHomyChghbf-UMLUxk7',
        'http://drive.google.com/uc?export=view&id=1R3DOELLrdZn4Cyar-DlekOga9DYtwrSV',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1YAH8PxxEZdgNCGwtSkvbuaiTjyS3ZgcM',
        'http://drive.google.com/uc?export=view&id=1nb7LaN9tB1ZF6LS5o13eeu8VdFl0bDOx',
        'http://drive.google.com/uc?export=view&id=12GkMXUZfvxPB_QM23x-Q0OG8vL5nsboT',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1ajsZPwfV8kKUDoahEVNuYXvtp-BUxQlj',
        'http://drive.google.com/uc?export=view&id=16jG_zhGkD9ulTDWXx9HCiW1czFEr-daw',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1f7fX0NFGh8juUWscaJWnoLZOvLVN5RmR',
        'http://drive.google.com/uc?export=view&id=1guQ8wStSqWCgBGCUrnFoUUOd9eQ3qct5',
        'http://drive.google.com/uc?export=view&id=1W8zh0UHpkPY3L9igr9lXdAeuaCdhKTaA',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1XrLRa8nbq45PotAqV2Fee8bVN7c1G8D3',
        'http://drive.google.com/uc?export=view&id=1Tv6Cm83z5FzlksmE6_SO1Vw74irfnWpN',
        'http://drive.google.com/uc?export=view&id=1FBoH4PIXlahGxzTWpNGjKCKbc7ZvXJao',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1nJqW-AeOOkZxZhCLw83eB9LbtN2nUmAb',
        'http://drive.google.com/uc?export=view&id=1sl1weQPNX-riYYAz7oXStJopf3UmnlvF',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1vr6zKRQYae_3jiku9ARTQWZK-P-vSdoc',
        'http://drive.google.com/uc?export=view&id=19ttDLomHefojdqAh9PVRHlHYLVaunjeT',
        'http://drive.google.com/uc?export=view&id=1X69i1k5Oskf_NNUGLWrHbe9EvS7dn-oh',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1RCnV8Jnq68_rY9EhdH6lKTqxFIeDAWtd',
        'http://drive.google.com/uc?export=view&id=1gBaFr5TTMrtPu1RAbVobxtTFlJciLuga',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1574E5tgjdlRPuaoVwMHx1m_cc3OtpN29',
        'http://drive.google.com/uc?export=view&id=1iqNie8sUDkvCfhpRfM57Ri3vvmBA4s73',
        'http://drive.google.com/uc?export=view&id=1vb38ML1mUhWzMhDmLNAWFnPcL5UN7qxg',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1kBbJZY8rCa7OkiCt44G794P3It-2pyM2',
        'http://drive.google.com/uc?export=view&id=1afoeF-02MTyg0MLNSzQBGLAwuiEL2ekk',
        'http://drive.google.com/uc?export=view&id=1wBqeybzvuxcUX9JOo9ZAVyl8fhCJ_whB',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1ze_Bq6Kya7l0WAjoaUDecE8Ib58ZSbr8',
        'http://drive.google.com/uc?export=view&id=10joL4zcPSEF6c5elGHpcmtw2DCY9SqJf',
        'http://drive.google.com/uc?export=view&id=1ad6X7FeUUCYeg1VS6REPbEVmHTgF-1kV',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1ylRQiWsRLSpwsN3jbHxzDNL860_K5A5J',
        'http://drive.google.com/uc?export=view&id=1BPkdMEQH_Bf1U_f87frc6bYBNZ1J3GR_',
        'http://drive.google.com/uc?export=view&id=1iIZIrzdbJ6bP8FggJ2CCxQyhWbGts43B',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1KBsmGKG409Y_ChHAKHQ93s09s86NEuUs',
        'http://drive.google.com/uc?export=view&id=1MxptbQa2bnJNTUBWkOy-xC_e1vRTdPRn',
        'http://drive.google.com/uc?export=view&id=1TyeXD7eZ_XOfiLWyVP4Bn_fLrisnRX6G',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1VtEc-xCuhJuZ384iC29gcdTT7gGkXuK0',
        'http://drive.google.com/uc?export=view&id=1PuksnA4_lnlN5bwyfz577WasCUo8EDx7',
        'http://drive.google.com/uc?export=view&id=1FADbkytN8eUc_F43LvOjFyH26s1FvCAv',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1dHg4OLPyOa3onYMSizL3rAkmQtw4ere0',
        'http://drive.google.com/uc?export=view&id=1NE1PFsu5Hj4Xy_DkgWSwtUBcIwzw3n1_',
        'http://drive.google.com/uc?export=view&id=1tHCD0hR3mIZrr5xSME3oXOzyknUS8ABK',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1xInQFqDf6yP3Ww_9sQyu4VVb7sF8k9Mc',
        'http://drive.google.com/uc?export=view&id=15HZ8YI4Z9kiVqsphhBwkW5Ob5L2rjngg',
        'http://drive.google.com/uc?export=view&id=1KhEcJSIpdE-fPPEgEtcKsmdx8LV-DIU9',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1d2Drr6zKvL7HYOVKw3A5WGICnbOtr1oL',
        'http://drive.google.com/uc?export=view&id=1quO1v27Eagfnt9LSr2U_Zxekg31JKuho',
        'http://drive.google.com/uc?export=view&id=1c9LaMAkNZupYK3W7bUjZtvc5joXCNViw',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1qj-oaUB9FEN0cHLrffu-xQZr7m11UEKr',
        'http://drive.google.com/uc?export=view&id=17d5O3LFKPqh-hQ_19bJCGeuLE4H_p10T',
        'http://drive.google.com/uc?export=view&id=1lWD0rUlMXg-wAH9Xm6tKvPQ2T9FwQyDJ',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1i0h5Zddog9wjBSTjBDq4joiO_RruvJBH',
        'http://drive.google.com/uc?export=view&id=1tsu-rVadMKBSna4aiXT6dhSy8HqPttno',
        'http://drive.google.com/uc?export=view&id=1G6NfvR_CtYUb8G6wUEFmmYlpCyk3Tkdk',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1LoJowgGYT2Ty4G6I2CEY3j_Daz6xiJ_T',
        'http://drive.google.com/uc?export=view&id=1fIrfsDQ5momOepxHnvvY5FJ1jHxuvxLt',
        'http://drive.google.com/uc?export=view&id=14xBnyt9FZXqippwOickXkyWcofSE6NyE',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1PbhhhwqqJTKBLWxT0oQ6NKsdje0W_6wW',
        'http://drive.google.com/uc?export=view&id=1D6vrrXgjH1R8vvKB1bYSB15WDUbwPAQ3',
        'http://drive.google.com/uc?export=view&id=1zex1sSiSW9JRlZj0zuFQsf_O4KJvG61C',
    ],
    [
        'http://drive.google.com/uc?export=view&id=178KeWnenFV3-AYFiBYlqWulJLtGM1HWP',
        'http://drive.google.com/uc?export=view&id=1D1aaYGMA72wRmDafsdgCKZN52ObZg6TC',
        'http://drive.google.com/uc?export=view&id=1F7VcYtzh2staGB-yWssIzZoSpaGZ40QN',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1uqCjHkeG7M43uamW8UTTuKVMi04t5vEE',
        'http://drive.google.com/uc?export=view&id=1WzJNiGVm7APhL4qX-75O04jGWYJdjeNr',
        'http://drive.google.com/uc?export=view&id=1yHZX5_I2Xc8gLuP3AHp8kDPC4QsL9M-G',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1LQg6cvU40DJZQiQAezv-sbbWC5It9ECl',
        'http://drive.google.com/uc?export=view&id=10uQhoV-ShVbhw6pV4_87sZ0T8oaurbui',
        'http://drive.google.com/uc?export=view&id=1MRg4rvOGIqSsj75fc0rJY5qHhMonJTed',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1JTHB9e5GiwBBrO7o9u3j4trW-X_mNYvN',
        'http://drive.google.com/uc?export=view&id=1LxQZbySlBOtWgNJ1Xh0HPvaYQY0MHFCh',
        'http://drive.google.com/uc?export=view&id=1IZWj3arBqIKnm1kEyWHW2qgVKGb0T6xU',
    ],
    [
        'http://drive.google.com/uc?export=view&id=14VEQPdgLxcO04aZx-uRwFExDFLRn2ayX',
        'http://drive.google.com/uc?export=view&id=1Yiea8Z0k5owHiVgg840bf1cPP0b_Pe65',
        'http://drive.google.com/uc?export=view&id=1eK92GzeLKmPtlpol6C76iOwnwLC7HbYL',
    ],
];
let blured = [
    [
        'http://drive.google.com/uc?export=view&id=12gFnyA2Gylb1r7LtQZZS5rzD8YGBCNtL',
        'http://drive.google.com/uc?export=view&id=1du_KdpaLoNmIOuiRxMbOLX6zdBMy2B9j',
        'http://drive.google.com/uc?export=view&id=1628WDOiAJYvLrHHgbU_0rKAtpdpLepLN',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1jZ_QyupiQbva8EhMkX49rX6AS7MvGO_m',
        'http://drive.google.com/uc?export=view&id=1Y_GcA_Mp4vUZi54roMSdRTupk4KjK3UU',
        'http://drive.google.com/uc?export=view&id=12BxqUDAw_LSLDSW4mSC-Q2vhsOdlvsaf',
    ],
    [
        'http://drive.google.com/uc?export=view&id=17GSTOlk0FjVcBfrGYhBiS9IMGBYQZITF',
        'http://drive.google.com/uc?export=view&id=1KQseUBB4MLA4WjwpYFtuvf4KfbBmIVXB',
        'http://drive.google.com/uc?export=view&id=1aEnra9V_mc99T4mL9jjOjjWpAawpsYRH',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1MSuz506fkYUzeldTDISfiCU9pRXmSmyT',
        'http://drive.google.com/uc?export=view&id=1L4bRcSxHYCNZoEh9T4W7gNY2l4ptInss',
        'http://drive.google.com/uc?export=view&id=1NsAtrqVbzOhFTPWVchP1DYb3dQd3en19',
        'http://drive.google.com/uc?export=view&id=1z6I9iHlHKgsms5k9yMVOD3l-vj24EBvT',
        'http://drive.google.com/uc?export=view&id=10OusjB5rpHIfGdcauXjwUcGtcRfxHsX3',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1hQjf-Lu4CDGAJffWVABSlKo4Um5EnvBB',
        'http://drive.google.com/uc?export=view&id=1aEC-gWzjtWXy8sXQk6zu4jZ6b16wdsid',
        'http://drive.google.com/uc?export=view&id=1FbhL8CH2nJ-CBevHyaNCHtjNScEkY7WX',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1bLLl1EueEnPSkNUTo7aJfLAF_U6X9FEZ',
        'http://drive.google.com/uc?export=view&id=1mMlOQQfpyy2sRBZ5DZUC7S9jCua63V0D',
        'http://drive.google.com/uc?export=view&id=131znL4PJZcmI4M-UfsatYLdt8C8F9yeC',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1P7qx-sQr_P5dai1HjNRiWHkohWNwHwPK',
        'http://drive.google.com/uc?export=view&id=18IVT0XzKtj2KeOBqNl_UwFhBA_CFgJ-U',
        'http://drive.google.com/uc?export=view&id=1L7zK6L_7SXjQMBYwJOJry-o6gqQ84d2i',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1j-qcTL2jBCYE4aUlvIv8flB_cf0KQrj0',
        'http://drive.google.com/uc?export=view&id=1X7vWK0vr0HgGM-36eTT57H4I2Z_1IK0P',
        'http://drive.google.com/uc?export=view&id=1nuDpjV95aXKSiSYoZzkHVjmjduyCRv7Q',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1ovol1ghWeXFY_SA6UcjM2I20Symdo5M5',
        'http://drive.google.com/uc?export=view&id=1ciLzf5iw_hSbaY-9_ueyEwPPkT-vlmqT',
        'http://drive.google.com/uc?export=view&id=1TGBCcN1cGGM7yFwloWTB8ft4PA34kXwu',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1K0xiMYVkBbbhGldrIf36ggdHHv7lNyk4',
        'http://drive.google.com/uc?export=view&id=1poUzu9b2YQFxfvE2H7Tl97etXzLmyrXd',
        'http://drive.google.com/uc?export=view&id=1ULFvN7Pth4nanYPEt-4Uzft7BiQSMScP',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1I8AMa3zFqJracYhSKYNP2Hcrumuk6YGZ',
        'http://drive.google.com/uc?export=view&id=1gZLk-77pwglDSw-alZtVYofzzIHbtq14',
        'http://drive.google.com/uc?export=view&id=1cDxKDxD0NJQ9AyElJla_ZkhEnvmfI6kR',
    ],
    [
        'http://drive.google.com/uc?export=view&id=11f8KCRrdzOIlRuGe_srxfAk6vUTQ08GL',
        'http://drive.google.com/uc?export=view&id=1wdUzr4EQm24UzaylV8Xq3xpAxFc82EB1',
        'http://drive.google.com/uc?export=view&id=1d8xKh2EZt1YsEk4CEwhF26YKCaep-10-',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1QN61LhaNgLoJKH98u6isF1lYW0IWHoxH',
        'http://drive.google.com/uc?export=view&id=1G1XGwZ7hIyb6R_KNyi25Wg6FW33Q7Xz8',
        'http://drive.google.com/uc?export=view&id=1OktOzUQIp4-kDArdZp02vDpVAolRSByL',
    ],
    [
        'http://drive.google.com/uc?export=view&id=17oYPqNoLtU8dJ2gGgsKx83w5Fzc-zORq',
        'http://drive.google.com/uc?export=view&id=1guWA3bVIfb2ePKDooO6PDZWfEl7g2epY',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1ZtJDj4g0BRuvVv7Sp7LwsCugvCBCskH5',
        'http://drive.google.com/uc?export=view&id=1ccz6QatwlAzbf92ePRXzAkYkKse994Dq',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1Ud6sTLuTzix6dnk-duX45WOImT8gyFTg',
        'http://drive.google.com/uc?export=view&id=1Z2cciHROqhdDk5PjfG0c3S-_q_necsYn',
        'http://drive.google.com/uc?export=view&id=1zS2d8O1xhU1KDmhb51OXEJZev4vyrNL_',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1RaIUxl3pdZop2Xa02Thz5Ch5a79XTTJ2',
        'http://drive.google.com/uc?export=view&id=1b9liqDMbMEBe-EsCVReqjp_mqoz19ytB',
        'http://drive.google.com/uc?export=view&id=1RSFKdLgOcg6kCK-Y-vPeOstMAlVNKO63',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1vE9qvYtgN_SxBwN8zub_J4nEDCb1JsZs',
        'http://drive.google.com/uc?export=view&id=1EoJ5YgCBqgxBext0QmOubJHqhL4kRoYF',
        'http://drive.google.com/uc?export=view&id=1jtCpoIMF-9ygBV-NlJ_eCIrfuXpKhlwI',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1rVgKKIpW3WNL31ioMmVm7lyH8s4WwhTU',
        'http://drive.google.com/uc?export=view&id=1eDeJ3mufDDK3cdSq7IcsLslAzetATPzc',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1XeCNHgSPmKHu-f54QRv_lwV4sX6TliGB',
        'http://drive.google.com/uc?export=view&id=19MjByU6aaGiah6X-Y0_G_zJ6TlwM0mCR',
        'http://drive.google.com/uc?export=view&id=19t7l_yJzD11pXJk7XdfcyLdlo-jwoXQk',
    ],
    [
        'http://drive.google.com/uc?export=view&id=16WHxPTuCXPIIPTdml0sPn_PL2uTd4azo',
        'http://drive.google.com/uc?export=view&id=15SmoQeeEAh3tV0d9P5oSrWbw-dDYBBBN',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1iQvQgbHdCI1oX7D2YYHBzg-w3g2Xjns-',
        'http://drive.google.com/uc?export=view&id=1H-pUFR332lUyrDZvt3HSsRAnoXGkAc75',
        'http://drive.google.com/uc?export=view&id=1UdlEJEYrD7MXIVZHOv7QDJnK3tHeuPPo',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1sIExNv2ec91dD6ljGNiIeXoCgXUzNSxP',
        'http://drive.google.com/uc?export=view&id=1Z3UJAWuSVVBff4h-9-EXHiUpiawdAZp0',
        'http://drive.google.com/uc?export=view&id=1CrwtWCKB3vvmiv7s8KIMRrE0LQ1pi7Hl',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1Q5XVCZdChJKnfV3BkPBcWwVv7CJ3_4dc',
        'http://drive.google.com/uc?export=view&id=1ascQY6H9RpfD_-LtcCgCeAQ5OZgbbZEr',
        'http://drive.google.com/uc?export=view&id=1f0gNcpHmlf39TQ42ywAKvG821X9L-9Wr',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1zhdD_NTEt3vHtF_-e18ttaSFIz1GMA-x',
        'http://drive.google.com/uc?export=view&id=1plQViJL4IBVZjvb17r4YNm0GUEIKG_Yf',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1na4AVQBxfANKBPglkx84qZ0z18nQx0TH',
        'http://drive.google.com/uc?export=view&id=1UrKR2rAgLPSk1eBDM6cSyihbOaBg9niE',
        'http://drive.google.com/uc?export=view&id=1OAr4dEOP-fCAAWDapq3bKv5uy6uhhPdG',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1PRUC5rkOI2Fj0Seg5LkhkrBqLCoElN2p',
        'http://drive.google.com/uc?export=view&id=1tiQ1LdgJwGKSk4A5zeF6ph2syd3Gs4l9',
        'http://drive.google.com/uc?export=view&id=1noPWu-F4Rc4Tgo-layJgtmWVOFoREZwd',
    ],
    [
        'http://drive.google.com/uc?export=view&id=19MCAcm1Kgkgxv_DL7UAfkxp4Sm3gjt0G',
        'http://drive.google.com/uc?export=view&id=1wgi33I_5axMVyE3dLsxIXNQkjedAFOUE',
        'http://drive.google.com/uc?export=view&id=1tcUMNaKyuFrW5sZx1jgqga2t8DA-TqGQ',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1FGuUk07HHTJG-gmVqXcZNEGXKKBTP5uG',
        'http://drive.google.com/uc?export=view&id=1la_Fs6w6Zxplc7hjMO8jqJLHN735EkRz',
        'http://drive.google.com/uc?export=view&id=1DWwwPMQKV7rLHm9hG1CnRc0N79Wvf7D0',
    ],
    [
        'http://drive.google.com/uc?export=view&id=19w4wPGPU0ykFt-kWPVLgB6ke6yvTNvf2',
        'http://drive.google.com/uc?export=view&id=1_F34zC3RKNfOYJMsnkivMrp7tWuWefdi',
        'http://drive.google.com/uc?export=view&id=15DkeQpM_M3yR900zjpCouzFoaqZkTf_5',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1ibe6ML3yR84lrgaRv2qsBHFwsXXayUQf',
        'http://drive.google.com/uc?export=view&id=1RgFnKd_4b5GN0fObYnwF6hAZZDHs7Gx3',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1kzTw6Qo3Vs7Ov4OeGRGj_ZI1aKaHLl3P',
        'http://drive.google.com/uc?export=view&id=1e3tDdI_guF0Oo9yd8-EtnuYPgbIjdvjD',
        'http://drive.google.com/uc?export=view&id=1_DNmctZXUviwnH8ynNBePXHOKOmvRCSx',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1NzU77eZnrEVWnAOZISGJFKUckHMauBd7',
        'http://drive.google.com/uc?export=view&id=1tcsMC6Yt6ygiqKqvTHROz6m5o88OlFXd',
        'http://drive.google.com/uc?export=view&id=1MFQk8OI8HGcptrBl16gQit94MIV5fs_C',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1S6CeX4dU17d6RdehTfT1qwTGa806E_xs',
        'http://drive.google.com/uc?export=view&id=1UrgEguNbZB88LXybWSlEt6tmc0x5coRx',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1D0XzAT-qIxPhCbNbt1lj3y5_OtVMGN9E',
        'http://drive.google.com/uc?export=view&id=1Fy1T-vZKoVleQszxBVqw8dKbY-oYPH0s',
        'http://drive.google.com/uc?export=view&id=12Ouzt6l3Eq-xRBN12ZTQCWX-rD6drhZJ',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1PsBn6_gK5PmT488VvHnTKKolV1r83Q3n',
        'http://drive.google.com/uc?export=view&id=1C07mj--WxGtNvOli_Jm9HPUqIgXhqCWN',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1boPulJnlrzngtZxBSImoIHfS1IsK7_9U',
        'http://drive.google.com/uc?export=view&id=11nhd_ViJCQlM-rqUDWvvBBzyp9mGplGn',
        'http://drive.google.com/uc?export=view&id=1hC7Yg3c6Ug5hhIc7CijJMXqfb4q99G66',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1S8yUGngI_RuJyWHrknY43U8djAY_O1TW',
        'http://drive.google.com/uc?export=view&id=19ruk5D3FHoUtNa48NecWu14q07vUmw_g',
        'http://drive.google.com/uc?export=view&id=1VuuGpWcvZiXRsDiUVs8F_zPySdn4Wuhp',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1PRsGCMRNumxmB3F38yiyXQ5-PdOmevBV',
        'http://drive.google.com/uc?export=view&id=1EZNRH4NxH7W37thuCxxEZ-AFfk13wmUJ',
        'http://drive.google.com/uc?export=view&id=1IOm10Qj9y2GjMdr7CFyRKZlrG7ft7MsG',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1_63CdWkV5IDXqY2cDp3QliHGaxv-Ljz7',
        'http://drive.google.com/uc?export=view&id=100ZffCIh4Can95o7rx-laTmD2Epumjot',
        'http://drive.google.com/uc?export=view&id=1rY6JzRZNb-iB47xTOIMbN8Y47JSpGxnR',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1K7g0K75Q2LqpURMdREvxWlnGwpM_TZ7c',
        'http://drive.google.com/uc?export=view&id=1_wOF-r3wWBJEJHjT7h5QgWY2BEdHmw0z',
        'http://drive.google.com/uc?export=view&id=10vgCZJfbRsOzkzCmH9o8tzZVFkm811z_',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1yug9COhHUvj-tw-ivwt6zyt0hO6MW_iL',
        'http://drive.google.com/uc?export=view&id=1oizJ_pdsD72Rd5HRj8Dp6AvQ3g8xJg47',
        'http://drive.google.com/uc?export=view&id=1eeFfgEmYbNv3hehKw-2XiLsvhBuJgqMJ',
    ],
    [
        'http://drive.google.com/uc?export=view&id=169FfPpA5sr37gNIoblwQRJdDzKdDEtOp',
        'http://drive.google.com/uc?export=view&id=1wSLgf6j5ygNAy70xvUQg4fBOIFtl-_Lg',
        'http://drive.google.com/uc?export=view&id=1kZzc1zABmF_WN8VBjpDll7n3XbHnQOqn',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1d7TZAjv0ksq9FUznYPvGymte67V5AdlH',
        'http://drive.google.com/uc?export=view&id=1-xc0hz7WgYeBT40DHFxsh0VqYy8I5FUX',
        'http://drive.google.com/uc?export=view&id=1ZuiVbHpTCqDjiRdYSZiSNeFnoj2HtSp-',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1aoJVau3401vvKmuoM3-c1XzYWBZizseP',
        'http://drive.google.com/uc?export=view&id=1Y-DoEERfweAFAUa7DuFl3FPsKtcT7t4q',
        'http://drive.google.com/uc?export=view&id=1NfNcIldsQHLrWJVN45KgX8O5hUgx1GiL',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1Q1VBYsqYTyfS4yg4cDI30-D8Oaha7lJ6',
        'http://drive.google.com/uc?export=view&id=1ZvQ5Ih7phyhF1AcHLP0JYt29mzkpcO2k',
        'http://drive.google.com/uc?export=view&id=18FOtTRcSrrRMtzqOaBBMGsWARJzTTSsm',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1sP-zA4jD6G9j-LF5almK_I5j06r6GJgC',
        'http://drive.google.com/uc?export=view&id=1rDpWuQno8i3zPVzAk_b9JTCPIJiMEV54',
        'http://drive.google.com/uc?export=view&id=1DTAzoi6_-eApo8h9Drm4VmasFoFQykDN',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1e0WzGQ884_FuOtUU3pAeLt1X8JaoiUTl',
        'http://drive.google.com/uc?export=view&id=1Tlvgnvs46pLgQw5hkQRWr_BzhA6Swcne',
        'http://drive.google.com/uc?export=view&id=1e8R7sb5vQWdizFOQWgxOWSyhuUnYC4kv',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1Jbkn0OqLI_aBgyvDvOSD4ilayHIJ6RbP',
        'http://drive.google.com/uc?export=view&id=1utHYplm9_4Mmcjdc_T31s8zIYrV--vCz',
        'http://drive.google.com/uc?export=view&id=1sOBhxlhM47WE9qlhuP6fUY4iyp222NUg',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1qOJo_6CO163IaNZeM0LIM1amNynXlOfJ',
        'http://drive.google.com/uc?export=view&id=1imfOhpereWyV3qF9cRlJ6CQpQyp31-AU',
        'http://drive.google.com/uc?export=view&id=15hGfzuOnSqt7PLlGzXIIpdutimS0u6fh',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1L2K9uoKvIYvIWqyr7aoqm-YvIgrDN8vs',
        'http://drive.google.com/uc?export=view&id=1P_nqcb2VCK9hqYpRZT856fpbuaEUrPIQ',
        'http://drive.google.com/uc?export=view&id=1NobTbWx3S8ZV2DQ2ZDNSSZSmAFFEnPqr',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1f2ch2EBoP-uwAaJkVUE623Rw2iegkDy4',
        'http://drive.google.com/uc?export=view&id=1GhpRp0QTlq5GFMTavI1gQv4jclUsqPaw',
        'http://drive.google.com/uc?export=view&id=1O5jUPLozc1JXq4Qk8O83YzpErhW8wY9y',
    ],
    [
        'http://drive.google.com/uc?export=view&id=171SFLb2cnDT_1-WGyYqGLzgvp_jwboDj',
        'http://drive.google.com/uc?export=view&id=1L-vLBMJ2FJKuU34a7Z9HbkfE5AfEEuDd',
        'http://drive.google.com/uc?export=view&id=189ZFxF0ErOTc7Vzi9Gc42I8kx9B0WKXD',
    ],
    [
        'http://drive.google.com/uc?export=view&id=1xiTqqF6J_Kovc5ss2z6-umqkFbSvbXFy',
        'http://drive.google.com/uc?export=view&id=1zKL57qYZOKVFKskw2SlcLHKozdLBtWKk',
        'http://drive.google.com/uc?export=view&id=1A1ajDFu1yy6m4LjXdDCsGf29tZW8p2Ws',
    ],
];
let categories = [
    'shoes',
    'shoes',
    'shirts',
    'shirts',
    'shoes',
    'shoes',
    'shirts',
    'shoes',
    'shoes',
    'shoes',
    'shoes',
    'jackets',
    'shoes',
    'shoes',
    'shoes',
    'shoes',
    'pants',
    'shoes',
    'pants',
    'jackets',
    'jackets',
    'jackets',
    'shoes',
    'jackets',
    'shirts',
    'pants',
    'shoes',
    'shirts',
    'shoes',
    'shoes',
    'shirts',
    'shoes',
    'shoes',
    'shirts',
    'pants',
    'shirts',
    'shirts',
    'shirts',
    'pants',
    'jackets',
    'shoes',
    'pants',
    'shirts',
    'pants',
    'shirts',
    'jackets',
    'shoes',
    'shirts',
    'shoes',
    'shirts',
    'shoes',
    'shoes',
    'shirts',
    'shirts',
];
let marks = [
    'adidas',
    'adidas',
    'rebook',
    'puma',
    'rebook',
    'rebook',
    'rebook',
    'nike',
    'puma',
    'adidas',
    'rebook',
    'rebook',
    'rebook',
    'adidas',
    'adidas',
    'adidas',
    'nike',
    'adidas',
    'puma',
    'adidas',
    'puma',
    'nike',
    'adidas',
    'nike',
    'puma',
    'nike',
    'adidas',
    'adidas',
    'nike',
    'puma',
    'puma',
    'nike',
    'nike',
    'nike',
    'adidas',
    'nike',
    'adidas',
    'puma',
    'nike',
    'adidas',
    'nike',
    'adidas',
    'adidas',
    'adidas',
    'adidas',
    'adidas',
    'nike',
    'puma',
    'nike',
    'adidas',
    'nike',
    'nike',
    'rebook',
    'adidas',
];
let features = [
    'modern and looks awesome and stylish',
    'comfortable for sport',
    'budget friendly price',
    'the best in the market',
];
let colors = [
    ['#46ddb2', '#c91818'],
    ['#D81E19', '#2491DB'],
    [],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#a82eea'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#D81E19', '#2491DB'],
    ['#D81E19', '#2491DB'],
    ['#D81E19', '#2491DB'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#D81E19', '#2491DB'],
    ['#1a508b', '#810034', '#28b5b5'],
    [],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#d82222'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#a82eea'],
    ['#da2525', '#1be497'],
    ['#1a508b', '#810034', '#28b5b5'],
    [],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    [],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
    ['#1a508b', '#810034', '#28b5b5'],
];
let sizes = [
    ['37', '38', '39'],
    ['42', '41', '40', '39'],
    ['39', '40', '41.5', '43'],
    [],
    ['39', '40', '41.5', '43'],
    [],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['40', '41', '42'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['42', '41', '40', '39'],
    ['42', '41', '40', '39'],
    ['42', '41', '40', '39'],
    ['39', '40', '41.5', '43'],
    ['42', '41', '40', '39'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    [],
    ['40', '41', '42'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['40', '41', '42'],
    ['38', '39', '40', '41'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    [],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
    [],
    ['39', '40', '41.5', '43'],
    ['39', '40', '41.5', '43'],
];
let quantity = 100;
let user_id = 'a13ad179-57bd-4a32-90f0-1460a95e426a';
let productsS = [];
images.forEach((x, i) => {
    let price = Math.floor(Math.random() * 1000);
    let data = {
        title: titles[i],
        price,
        images: images[i],
        blured_images: blured[i],
        sizes: sizes[i],
        mark: marks[i],
        quantity,
        user_id,
        description,
        features,
        category: categories[i],
        colors: colors[i],
    };
    productsS.push(data);
});
exports.productsDD = productsS;
//# sourceMappingURL=x.js.map